language: nix
nix: 2.1.3

script:
  # node2nix produces a lot of output on stderr which causes Travis to say
  # "The job exceeded the maximum log length, and has been terminated."
  # There does not appear to be an option to turn this off so redirect it to file
  - cd pkgs/development/node-packages && ./generate.sh &> log.txt
  - cd pkgs/development/python-modules && ./generate.sh
  - cd pkgs/development/r-modules && ./generate.sh
